print("----------EJERCICIOS DE TUPLAS----------")
print("----------EJERCICIOS FACIL----------")
print("Ejercicio 1: Crea una tupla con los nombres de tus amigos. Imprime el primer y el último nombre de la tupla.")
my_friends_tuple = ("Santiago","Joya","Juan","Pedro","Pablo")
print(my_friends_tuple[0])
print(my_friends_tuple[4])    
print("-----FIN-----\n")
print("Ejercicio 2: Crea dos tuplas: una con frutas y otra con verduras. Concátenalas en una sola tupla e imprime el resultado.")  
my_fruits_tuple = ("Manzana","Pera","Naranja")
my_vegetables_tuple = ("Zanahoria","Lechuga","Tomate")
my_fruits_and_vegetables_tuple = my_fruits_tuple + my_vegetables_tuple
print(my_fruits_and_vegetables_tuple) #Se imprimen las tuplas concatenadas en una
print("-----FIN-----\n")
print("Ejercicio 3: Crea una tupla con números repetidos. Usa count para determinar cuántas veces aparece un número específico.")
my_repeated_numbers_tuple = (1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,3,4,5,3,3,6,7,78)
print("El numero 3 se repite:",my_repeated_numbers_tuple.count(3), "Veces")  
print("-----FIN-----\n")
print("----------EJERCICIOS INTERMEDIO----------")
print("Ejercicio 4: Crea una lista de números. Convierte la lista en una tupla usando tuple(). Luego, convierte la tupla de vuelta a una lista usando list() y añade un nuevo número.")
my_numbers_list = [1,2,3,4,5,8,23,5,7,8,9,0]
my_numbers_list = tuple(my_numbers_list)
print("Impresion de los numeros como tupla -->", my_numbers_list)
my_numbers_tuple = list(my_numbers_list)
my_numbers_tuple.append(100)
print("Impresion de los numeros como lista y agregandole el valor (100)-->", my_numbers_tuple)
print("-----FIN-----\n")
print("Ejercicio 5: Crea una tupla con tres elementos: tu nombre, tu edad y tu ciudad. Usa el desempaquetado para asignar cada elemento a una variable e imprime esas variables.")  
my_personal_data_tuple = ("Santiago",22,"Bucaramanga")
name, age, city = my_personal_data_tuple
print("Nombre:",name)
print("Edad:",age)
print("Ciudad:",city)
print("-----FIN-----\n")
print("Ejercicio 6: Crea una tupla con diferentes nombres. Usa el método index para encontrar la posición de un nombre específico en la tupla.")  
my_names_tuple = ("Santiago","Joya","Juan","Pedro","Pablo")
my_names_tuple.index("Santiago")
print("La posicion de Santiago en la tupla es:",my_names_tuple.index("Juan"))
print("-----FIN-----\n")
print("----------EJERCICIOS DIFICL----------")
print("Ejercicio 7: Crea una tupla con dos números. Escribe un programa que intercambie sus valores sin usar una variable temporal adicional. Ejemplo: (a, b) = (b, a).")
mytwo_numbers_tuple = (1,2)
print("Valores iniciales:",mytwo_numbers_tuple)
mytwo_numbers_tuple = (mytwo_numbers_tuple[1],mytwo_numbers_tuple[0])
print("Valores intercambiados:",mytwo_numbers_tuple)  
print("-----FIN-----\n")
print("Ejercicio 8: Dada una tupla con los números del 1 al 4, crea una nueva tupla que contenga solo los números pares. Usa índices para acceder a los elementos específicos.")
my_numbers_tuple = (1,2,3,4)
my_even_numbers_tuple = (my_numbers_tuple[1],my_numbers_tuple[3])
print("-----FIN-----\n")
print("Ejercicio 9: Crea una tupla que contenga tres sub-tuplas: una con frutas, otra con verduras y otra con lácteos. Usa índices para acceder a cada sub-tupla y a un elemento específico dentro de ellas.")
my_food_tuple = (("Manzana","Pera","Naranja"),("Zanahoria","Lechuga","Tomate"),("Leche","Queso","Yogurt"))
print("Frutas:",my_food_tuple[2])
print("Verduras:",my_food_tuple[1])
print("Lacteos:",my_food_tuple[2])
print("-----FIN-----\n")
print("Ejercicio 10: Dada una tupla con las edades de un grupo de personas, encuentra la edad máxima, mínima y crea una nueva tupla con las edades ordenadas manualmente (sin usar sort ni ciclos).")
my_ages_tuple = (12,23,45,67,89,100,1,2,3,4,5,6,7,8,9,10)
print("El valor mayor de la tupla es: ",max(my_ages_tuple))
print("El valor mayor de la tupla es: ",min(my_ages_tuple))
sorted_ages = sorted(my_ages_tuple)
print("La tupla ordenada es:",sorted_ages)
print("-----FIN-----\n")